### ISSUE TITLE
Ubuntu 22.04 LTS  error

### ISSUE THREAD

**Issue by shangweikun** [cerebroapp/cerebro#567]
- [ ] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [ ] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 22.04 LTS**: 
- **0.5.0**: 
- **I do not know how to find it** _(See above how to open it)_: 

## Issue

I can not open the soft, and when I open it will be crashed

**Comment by dubisdev** [comment]
Hi @shangweikun

Yesterday we published [`v0.6.0`](https://github.com/cerebroapp/cerebro/releases/tag/v0.6.0). Although we haven't released the executables yet, you can try it out by following the [installation instructions](https://github.com/cerebroapp/cerebro#install).

Let us know if the error persists in this new version.

Thank you 🙌

**Comment by gabriellacerda** [comment]
Error persists, building on ubuntu 22.04 cerebro does not show anything... this also applies to ubuntu latest based distros, this happens due to ubuntu shipping with wayland from now, is this error happening on electron side or on cerebro side? This is the question.
Read more: https://www.phoronix.com/news/Ubuntu-2021-Success

**Comment by dubisdev** [comment]
Thanks for your response.

Wayland should be supported by [electron > 12](https://www.reddit.com/r/linux/comments/lw7cvk/electron_12_has_just_been_released_with_wayland/?utm_medium=android_app&utm_source=share)

Cerebro `v0.6.0` is using electron 19 so wayland shouldn't be a problem. Could you provide us any logs, like what does the console print when running `yarn dev`? 

Thank you,
David

**Comment by dubisdev** [comment]
Thanks for your response.

Wayland should be supported by [electron > 12](https://www.reddit.com/r/linux/comments/lw7cvk/electron_12_has_just_been_released_with_wayland/?utm_medium=android_app&utm_source=share)

Cerebro `v0.6.0` is using electron 19 so wayland shouldn't be a problem. Could you provide us any logs, like what does the console print when running `yarn dev`? 

Edited:
Just reviewed #573 and Cerebro seems to be working well in Ubuntu 22. So this must be a bug with something different than wayland.

Thank you,
David

**Comment by gabriellacerda** [comment]
![image](https://user-images.githubusercontent.com/8512862/185256498-1f0ffab4-9201-4aaa-9ac3-d2929e96f2cb.png)
Node.js v16.17.0, Npm 8.15.0
The long log of `yarn dev`
https://asciinema.org/a/rXvvLw9UdTtyi747AmSjYefBR

**Comment by dubisdev** [comment]
Yes it's weird. Does the application icon appear in the notification area when you execute the command?

**Comment by gabriellacerda** [comment]
> Yes it's weird. Does the application icon appear in the notification area when you execute the command?

yees!

**Comment by gabriellacerda** [comment]
I will try to debug here too...

**Comment by dubisdev** [comment]
Try to open the dev tools by clicking the icon and selecting development > open development tools (main and background)

Just to see if there are any logs.

BTW, `ctrl + space` does not show nothing?

**Comment by gabriellacerda** [comment]
Soooooooo problem solved... And here how reproduce our sincere exception...

1. First clone the repo
2. Then Install packages `yarn` will do the trick
3. Run `yarn dev` lmao
4. didn't like what u saw? stop the command, run `yarn build` and voilá! the ui is back...

I've also built an package .deb and installed from it, hope the people with bugs love it, as it's not bug anymore for me... :smile: :star: :turtle: :rocket: :star2:
I can upload to the repo the .deb and Image sir, jus give me perm :smile:

**Comment by gabriellacerda** [comment]
just one more question, no matter what word I write, there is no debounce? It is intentionally?

**Comment by dubisdev** [comment]
Cerebro failing to load the theme is a know issue. The error comes from the config file storing an old reference when switching between development and production. But this usually affects only to developers when testing, as end users normally download and install the package.

We are working on the CI so we can automatically publish the packages for different platforms.

For now, we would recommend users to build it's own package, as getting one from other source could be dangerous. Don't get me wrong, I could also upload the executable for Windows directly here, but it's much safer to generate your own until we configure the automatic releases.

**Comment by dubisdev** [comment]
And yes! For now Cerebro is not using any debounce. For now some plugins individually implement it, but not the core app.

**Comment by dubisdev** [comment]
Glad to see the app works!

@shangweikun does all this solve your problem?

Thank you 🙌

**Comment by gabriellacerda** [comment]
So I have created a fork with builds for linux, I've also added md5, if anyone need to check the files integrity, hope it helps! @dubisdev can u also share it with everyone in the another issues or in the readme? Thanks!
https://github.com/gabriellacerda/cerebro-linux/releases/tag/v0.6.0

**Comment by shangweikun** [comment]
Thanks.
